version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 626635440285.dkr.ecr.us-east-2.amazonaws.com
    
  build:  
    commands:
      # Build Order Dockerfile
      - echo Building API container from ./order/Dockerfile...
      - docker buildx build --platform linux/amd64 -t hw2/project2-order ./order
      - docker tag hw2/project2-order:latest 626635440285.dkr.ecr.us-east-2.amazonaws.com/hw2/project2-order:latest

      # Build Search Dockerfile
      - echo Building Worker container from ./search/Dockerfile...
      - docker buildx build --platform linux/amd64 -t hw2/project2-search ./search
      - docker tag hw2/project2-search:latest 626635440285.dkr.ecr.us-east-2.amazonaws.com/hw2/project2-search:latest

      # Build Web Dockerfile
      - echo Building Worker container from ./web/Dockerfile...
      - docker buildx build --platform linux/amd64 -t hw2/project2-search ./web
      - docker tag hw2/project2-web:latest 626635440285.dkr.ecr.us-east-2.amazonaws.com/hw2/project2-web:latest
      
  post_build:
    commands:
      # Push Order Image to ECR
      - echo Pushing order container to ECR...
      - docker push 626635440285.dkr.ecr.us-east-2.amazonaws.com/hw2/project2-order:latest

      # Push Worker Image to ECR
      - echo Pushing search container to ECR...
      - docker push 626635440285.dkr.ecr.us-east-2.amazonaws.com/hw2/project2-search:latest

      # Push Worker Image to ECR
      - echo Pushing web container to ECR...
      - docker push 626635440285.dkr.ecr.us-east-2.amazonaws.com/hw2/project2-web:latest
    
      - echo '[{"name":"product_lookup","imageUri":"626635440285.dkr.ecr.us-east-2.amazonaws.com/hw2/project2-search:latest"}]' > search_imagedefinitions.json
      - echo '[{"name":"order_processing","imageUri":"626635440285.dkr.ecr.us-east-2.amazonaws.com/hw2/project2-order:latest"}]' > order_imagedefinitions.json
      - echo '[{"name":"web_server","imageUri":"626635440285.dkr.ecr.us-east-2.amazonaws.com/hw2/project2-web:latest"}]' > web_imagedefinitions.json


artifacts:
  files: 
    - order_imagedefinitions.json
    - search_imagedefinitions.json
    - web_imagedefinitions.json