version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 626635440285.dkr.ecr.us-east-2.amazonaws.com
    
  build:  
    commands:
      # Build Order Dockerfile
      - echo Building API container from ./order/Dockerfile...
      - docker buildx build --platform linux/amd64 -t hw2/project2-order ./order
      - docker tag hw2/project2-order:latest 626635440285.dkr.ecr.us-east-2.amazonaws.com/hw2/project2-order:latest

      # Build Search Dockerfile
      - echo Building Worker container from ./search/Dockerfile...
      - docker buildx build --platform linux/amd64 -t hw2/project2-search ./search
      - docker tag hw2/project2-search:latest 626635440285.dkr.ecr.us-east-2.amazonaws.com/hw2/project2-search:latest

      - echo hello
  post_build:
    commands:
      # Push Order Image to ECR
      - echo Pushing order container to ECR...
      - docker push 626635440285.dkr.ecr.us-east-2.amazonaws.com/hw2/project2-order:latest

      # Push Worker Image to ECR
      - echo Pushing search container to ECR...
      - docker push 626635440285.dkr.ecr.us-east-2.amazonaws.com/hw2/project2-search:latest
    
      - echo '[{"name":"product_lookup","imageUri":"626635440285.dkr.ecr.us-east-2.amazonaws.com/hw2/project2-search:latest"},{"name":"order_processing","imageUri":"626635440285.dkr.ecr.us-east-2.amazonaws.com/hw2/project2-order:latest"}]' > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files: imagedefinitions.json